#!/bin/bash
version=`java -version 2>&1 | awk -F[\ \"\.] '/^java version / {print $4}'`
if [ "$version" = "9" ]; then
  java -Xmx8G -cp `./classpath.sh bin` --add-modules java.xml.bind -Dlog4j.configuration=log4j.properties com.oltpbenchmark.DBWorkload $@
else  
  java -Xmx8G -cp `./classpath.sh bin` -Dlog4j.configuration=log4j.properties com.oltpbenchmark.DBWorkload $@
fi
